name: sphero_sdk
description: A Flutter SDK for Sphero
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  flutter_ble_lib: any
  rxdart: any
  basics: any
  buffer: any
  dartx: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
