name: sphero_sdk
description: A Flutter SDK for Sphero
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  flutter_ble_lib: any
  rxdart: any
  basics: any
  buffer: any
  dartx: any
  freezed_annotation: any

dev_dependencies:
  freezed: any
  derry: any
  build_runner: any
  mockito: any
  flutter_test:
    sdk: flutter

flutter:

scripts:
  gen: flutter pub run build_runner build --delete-conflicting-outputs
  genw: flutter pub run build_runner watch --delete-conflicting-outputs
