name: sphero_sdk
description: A Flutter SDK for Sphero
version: 0.0.1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  basics: any
  buffer: any
  dartx: any
  flutter:
    sdk: flutter
  flutter_blue_plugin: any
  freezed_annotation: any
  meta: any
  rxdart: any

dev_dependencies:
  all_lint_rules_community: ^0.0.11
  build_runner: any
  derry: any
  flutter_test:
    sdk: flutter
  freezed: any
  mockito: any
  test: ^1.21.4

flutter:

scripts:
  gen: flutter packages run build_runner build --delete-conflicting-outputs
  genw: flutter packages run build_runner watch --delete-conflicting-outputs
