name: sphero_sdk
description: A Flutter SDK for Sphero
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  basics: any
  buffer: any
  dartx: any
  flutter:
    sdk: flutter
  flutter_ble_lib: any
  freezed_annotation: any
  meta: any
  rxdart: any

dev_dependencies:
  abide: any
  build_runner: any
  derry: any
  flutter_test:
    sdk: flutter
  freezed: any
  mockito: any

flutter:

scripts:
  gen: flutter packages run build_runner build --delete-conflicting-outputs
  genw: flutter packages run build_runner watch --delete-conflicting-outputs
