name: flutter_sphero_sdk
description: A Flutter SDK for Sphero baseed of the gobot
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  flutter_ble_lib: any
  rxdart: any
  dartx: any
  buffer: any

flutter:
  # Nothing
